basic:
  platform:
  desiredNumOfRoutes:
  configExportLocation:
  configFileName(?):
container:
  localAS:
  neighbors:
    - address:
      asn:
    - address:
      asn:
  rid:
  imageExportLocation:
policy: