basic:
  platforms:
    - "platform1"
    - "platform2"
  protocols:
    - "protocol1"
    - "protocol2"
  addressFamily: "ipv4|ipv6"
  routeSource: "random|mrt|partial_random_mrt"
  routeExport:
    location: "<path to folder>"
    fileName: "fileName.json"

mrt:
  collector: "collectorName"

prefixes:
  quantity: #
  prefixLengthRanges:
    - value: "/#-/##"
      probability: %
  routeSeed: "<path to seed JSON file>"
  includePrivateSpace: False

bgp:
  aspath:
    mode: "2byte|4byte|24byte"
    quantity:
      - value: "#-##"
        probability: %
    includePrivateAS:
      - value: bool
        probability: %
  communities:
    mode: "standard|large"
    quantity:
      - value: "#-##"
        probability: %
    includeWellKnown:
      - value: bool
        probability: %
  nexthop:
    - value: "xxx.xxx.xxx.xxx"
      probability: %
  origin:
    - value: "igp|egp|incomplete"
      probability: %

ospf:
  routeType:
    - value: "intra-area|inter-area|external-type1|external-type2|nssa-type1|nssa-type2"
      probability: %
  metricRanges:
    - value: "#-##"
      probability: %

device:
  configExport:
    location: "<path to folder>"
    fileName: "<fileName>.txt"
  ios:
    localAS: #
    vrf: "<vrf name>"
    deployment:
      address: "xxx.xxx.xxx.xxx"
  junos:
    vrf: "<vrf name>"
    bgpGroup: "<bgp group name>"
    deployment:
      address: "xxx.xxx.xxx.xxx"
  bird:
  frr:

container:
  imageExport:
    location: "<path to folder>"
    fileName: "<fileName>.tar"
  configExport:
    location: "<path to folder>"
  bgp:
    localAS: #
    rid: "xxx.xxx.xxx.xxx"
    neighbors:
      - address: "xxx.xxx.xxx.xxx"
        asn: #
  ospf:
    rid: "xxx.xxx.xxx.xxx"
    areaID: "xxx.xxx.xxx.xxx"
  networking:
    mode: "dynamic|static"
    static:
      ipv4:
        address: "xxx.xxx.xxx.xxx/#"
        gateway: "xxx.xxx.xxx.xxx"
      ipv6:
        address: "<ipv6 address>/#"
        gateway: "<ipv6 address>"
  attributes:
    - name: "Comment"
      value: "Here's a comment!"

policy:
  constraints:
    - type: "prefix"
      action: "include|exclude"
      values:
        - value: "xxx.xxx.xxx.xxx/##"
          probability: %
    - type: "bgp_aspath"
      action: "include|exclude"
      values:
        origin:
          - value: #
            probability: %
        transit:
          - value: #
            probability: %
    - type: "bgp_communities"
      action: "include|exclude"
      values:
        - value: "1.2*:345*" # use . to indicate a single wildcard character and * to indicate a continuous wildcard sequence
          probability: %
    - type: "bgp_origin"
      action: "include|exclude"
      values:
        - value: "igp|egp|incomplete"
          probability: %

  overrides:
    - match: "xxx.xxx.xxx.xxx/##"
      except:
        - "xxx.xxx.xxx.xxx/##"
      strict: False
      attributes:
        # all of the same attributes available under the top-level "prefixes", "bgp", and "ospf" configuration
        # all constraints, EXCEPT prefix constraints, are also available
