[project]
name = "jargen"
version = "0.1.0"
description = "Bulk Route Generator for Networking Labs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "docker>=7.1.0",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]
